sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid L1 Power"
    register_type: holding
    address: 622
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid L2 Power"
    register_type: holding
    address: 623
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid L3 Power"
    register_type: holding
    address: 624
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Total Grid Power"
    register_type: holding
    address: 625
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid Voltage L1"
    id: grid_voltage_l1
    register_type: holding
    address: 598
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid Voltage L2"
    id: grid_voltage_l2
    register_type: holding
    address: 599
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid Voltage L3"
    id: grid_voltage_l3
    register_type: holding
    address: 600
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Daily Energy Bought"
    id: daily_energy_bought
    register_type: holding
    address: 520
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Daily Energy Sold"
    id: daily_energy_sold
    register_type: holding
    address: 521
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Total Energy Bought"
    id: total_energy_bought
    register_type: holding
    address: 522
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Total Energy Sold"
    id: total_energy_sold
    register_type: holding
    address: 524
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Internal CT L1 Power"
    register_type: holding
    address: 604
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Internal CT L2 Power"
    register_type: holding
    address: 605
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Internal CT L3 Power"
    register_type: holding
    address: 606
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Internal total Power"
    register_type: holding
    address: 607
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid Current L1"
    register_type: holding
    address: 630
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid Current L2"
    register_type: holding
    address: 631
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Grid Current L3"
    register_type: holding
    address: 632
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-External CT L1 Power"
    register_type: holding
    address: 616
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-External CT L2 Power"
    register_type: holding
    address: 617
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-External CT L3 Power"
    register_type: holding
    address: 618
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Out-of-grid–total power"
    register_type: holding
    address: 619
    unit_of_measurement: "W"
    device_class: power
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-AC Grid Relay"
    register_type: holding
    address: 552
    bitmask: 0x4
    device_class: power

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Force Off Grid"
    id: switch_off_grid
    register_type: holding
    address: 179
    bitmask: 1
